name: PlusPay
version: '${project.version}'
main: me.skythebuilder.pluspay.PlusPay
api-version: '1.20'
Author: Snowdesert
commands:
  pay:
    description: Transfer money
    usage: /pay <Player> <Amount>